spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_tt
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: true

file:
  upload:
    path: ./uploads/menu/

server:
  port: 8082